### ISSUE TITLE
Negative Order Date?

### ISSUE THREAD

**Issue by HumanGamer** [MooNag/steam-deck-calculator#19]
The calculator predicted I would get it in the first batch of Q1 but I didn't and now putting my information in shows negative numbers back to last monday for the moo dataset as well as the latest CSV.

rtReserveTime: 1626455515
Model: 512 GB
Region: US (actually Canada but that's probably counted as US)
Original Valve Prediction Before Delay: Q1
Updated Valve Prediction After Delay: Q2

![image](https://user-images.githubusercontent.com/39096122/162518565-892a3bec-1548-4e6b-a04d-e0ea9181d4ff.png)

**Comment by MinoDab492** [comment]
@HumanGamer If I had to guess, the calculator might not have actual support for Canada, and it might go off the USA, which would mean that it's using the wrong info. Which would mean that by that info your Deck should have already gone out, if you were in the US, since negative means that it's already gone out. I can try to add possible Canada support in my pull request, but zero guarantees.

**Comment by X3nophone** [comment]
Hello!

Negative just means it's past the estimated time. I'm in the same boat (also in canada) 

Here is the disclaimer on the page (I am not affiliated in any way)

**Disclaimer: This is an estimator. It creates magic numbers out of thin air. Assume the magic numbers are wrong. But copium is addicting!**

It's simply an estimate so it can certainly overshoot as we've seen.

Thank you,

**Comment by MooNag** [comment]
@X3nophone is correct. It is just an estimate. Negative means that the estimated date is in the past.
